[tools]
go = "1.23.1"
minikube = "1.34.0"
operator-sdk = "latest"
kubebuilder = "latest"
argocd = "latest"
helm = "latest"
oc = "latest"
kubectl = "latest"
k9s = "latest"
hugo = "latest"
java = "temurin-23"
maven = "3.9"
quarkus = "latest"
spring-boot = "latest"
jmeter = "latest"

[settings]
experimental = true
